id: AE305E919
title: Samantabhadra
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:28:18.655141
  last_modified_at: 2022-03-01 21:28:18.655148
